baseurl = "https://floads.io/"
languageCode = "en-US"
title = "Floads GmbH"
paginate = 4
DisqusShortname = "floads"
Copyright = "All rights reserved - 2019"
theme = "casper"

[params]
  description = "great things will come, soon."
  cover = "img/main-01.jpg"

  author = "Ivo Marino"
  authorlocation = "Baar, Zug"
  authorwebsite = "https://floads.io"
  bio = "Clound Engineering."

  # logo = "images/logo.png"
  # googleAnalyticsUserID = ""

  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  githubName = "floadsio"
  # twitterName = "floads"

  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
